# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8000/api/author/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTU2OTY5MjU3NCwiZXhwIjoxNTcwOTAyMTc0LCJuYmYiOjE1Njk2OTI1NzQsImp0aSI6ImZRUDJuVVlVdzMxdzY5YkMiLCJzdWIiOjQ5ODc5NTkzLCJwcnYiOiI3NjQ4YzVjMjgwNzY1NjEzZjczMjM1ZWE4NjdhZWY4ZjBlNWEwMzAwIn0.ohyvYj6O0M0bo1LsxgW3PS3N6IAf4k7y5kzhad7SoLE

{}

###
GET http://localhost:8000/api/author/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTU2OTY5MjU3NCwiZXhwIjoxNTcwOTAyMTc0LCJuYmYiOjE1Njk2OTI1NzQsImp0aSI6ImZRUDJuVVlVdzMxdzY5YkMiLCJzdWIiOjQ5ODc5NTkzLCJwcnYiOiI3NjQ4YzVjMjgwNzY1NjEzZjczMjM1ZWE4NjdhZWY4ZjBlNWEwMzAwIn0.ohyvYj6O0M0bo1LsxgW3PS3N6IAf4k7y5kzhad7SoLE

{}

###
GET http://localhost:8000/api/author/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTU2OTY5MjU3NCwiZXhwIjoxNTcwOTAyMTc0LCJuYmYiOjE1Njk2OTI1NzQsImp0aSI6ImZRUDJuVVlVdzMxdzY5YkMiLCJzdWIiOjQ5ODc5NTkzLCJwcnYiOiI3NjQ4YzVjMjgwNzY1NjEzZjczMjM1ZWE4NjdhZWY4ZjBlNWEwMzAwIn0.ohyvYj6O0M0bo1LsxgW3PS3N6IAf4k7y5kzhad7SoLE

{}

###
GET http://localhost:8000/api/author/1/tierlist
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTU2OTY5MjU3NCwiZXhwIjoxNTcwOTAyMTc0LCJuYmYiOjE1Njk2OTI1NzQsImp0aSI6ImZRUDJuVVlVdzMxdzY5YkMiLCJzdWIiOjQ5ODc5NTkzLCJwcnYiOiI3NjQ4YzVjMjgwNzY1NjEzZjczMjM1ZWE4NjdhZWY4ZjBlNWEwMzAwIn0.ohyvYj6O0M0bo1LsxgW3PS3N6IAf4k7y5kzhad7SoLE

{}

###
